name: Release
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: use REPO
        run:
          echo "The value of REPO is: ${REPO}"
      - name: Build and Push Docker Image
        run: |
          echo ghcr.io/${REPO}
          docker build --tag ghcr.io/${REPO}:latest .
          docker push --all-tags $IMG