name: Release
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and Push Docker Image
        run: |
          UNFORMATTED_IMG=ghcr.io/${{ github.repository }}
          echo ${UNFORMATTED_IMG,,}
          echo "IMG=${UNFORMATTED_IMG,,}" >>${GITHUB_ENV}
          echo $IMG
          docker build --tag $IMG:latest .
          docker push --all-tags $IMG